# -*- coding: utf-8 -*-
"""trabSimulacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ha-n9OE7WEfsYeEkUKceIiahgD1-KPON

# Trabalho de Simulação MAB-515
## Grupo:


*   **Alexandre Moreira**
*   **Daniel Atkinson**
*   **Rennan Gaio**
"""

import numpy as np
import matplotlib.pyplot as plt
import time
from scipy import stats
import math
import sys
# %matplotlib inline

class Fregues:
  def __init__(self, tempo):
    #variáveis que indicam marcos no tempo
    self.tempo_chegada = tempo
    self.__tempo_comeco_servico: time
    self.__tempo_termino_servico: time
      
    #variáveis que indicam duração
    self.__tempo_em_servico: time
    self.__tempo_em_espera: time
    self.__tempo_total: time
      
    #variável que indica se cliente já entrou em serviço
    self.__entrou_em_servico = False
    
    #variável que indica se cliente já terminou o servico
    self.__terminou_servico = False
    
  def entraEmServiço(tempo_comeco_servico):
    self.__tempo_comeco_servico = tempo_comeco_servico
    self.__entrou_em_servico = True
    
    #calcula o tempo que o freguês ficou em espera
    self.__tempo_em_espera = self.__tempo_comeco_servico - self.__tempo_chegada
    
  def terminaServico(tempo_termino_servico):
    self.__tempo_termino_servico = tempo_termino_servico
    self.__terminou_servico = True
    
    #calcula o tempo que o freguês ficou em servico
    self.__tempo_em_servico = self.__tempo_termino_servico - self.__tempo_comeco_servico
    
    #calcula o tempo total que o freguês ficou no sistema
    self.__tempo_total = self.__tempo_em_espera + tempo_em_servico

    
    
class EntradaLista:
  #evento == 0 indica chegada à fila
  #evento == 1 indica começo de serviço
  #evento == 2 indica término de serviço
  def __init__(self, evento: int, fregues: Fregues):
    self.evento = evento
    self.fregues = fregues
    
    #o tempo em que o evento ocorreu é o tempo de chegada do fregues
    self.tempo = fregues.tempo_chegada
    
    
    
class Fila:
  def __init__(self, tx_chegada:float, tx_servico: float, k: int, tipo_fila: int):
    
    #lista que será usada para efetuar o controle dos eventos que podem ocorrer no sistema
    self.__lista = []
    
    #variável que indica a quantidade de pessoas no sistema
    self.__n_pessoas_sist = 0
    
    #variável que indica a quantidade de pessoas na fila de espera
    self.__n_pessoas_espera = 0
    
    #variável que indica a quantidade de pessoas em serviço
    self.__n_pessoas_servico = 0
    
    #variável que indica o tempo total que se passou desde o início da simulação
    self.__tempo_total: time
     
    self.__tx_chegada = tx_chegada
    
    self.__tx_servico = tx_servico
    
    #quantidade de coletas a serem feitas
    self.__k = k
    
    #variável que irá contar a quantidade de coletas
    self.__contador = 0
    
    #simula tempo até evento da primeira chegada e adiciona essa entrada na lista
    tempo_primeira_chegada = self.simulaTempoAteEvento(self.__tx_chegada)
    fregues = Fregues(tempo_primeira_chegada)
    entrada_lista = EntradaLista(0, fregues)
    self.addNovaEntrada(entrada_lista)
    
  def simulaTempoAteEvento(taxa: float):
    n = np.random.rand()
    tempo = -math.log(1-n)/taxa
    return tempo
    
  def addNovaEntrada(nova_entrada: EntradaLista):
    #atualizando estado do sistema
    self.__lista.append(nova_entrada)
    
    #chegou uma nova pessoa na fila
    if (nova_entrada.evento == 0):
      #atualizando estado do sistema
      self.__n_pessoas_espera = self.__n_pessoas_espera + 1
      self.__n_pessoas_sist = self.__n_pessoas_sist + 1
      
      #preparando para gerar novo evento
      if (self.__n_pessoas_servico == 0):
        #se não tem ninguém sendo servido freguês imediatamente entra em serviço
        fregues = nova_entrada.fregues
        fregues.entraEmServico(fregues.tempo_chegada)
        entrada_lista = EntradaLista(1, fregues)
      else:
        #se tem alguém em serviço precisamos simular uma chegada e um término de serviço
        #o evento que ocorrer em menor tempo será inserido na lista
        tempo_chegada = self.simulaTempoAteEvento(self.__tx_chegada)
        tempo_termino = self.simulaTempoAteEvento(self.__tx_servico)
        #se chega alguém antes do freguês em serviço terminar
        if (tempo_chegada < tempo_termino):
          #não podemos esquecer de somar o tempo até a chegada com o tempo que decorreu até o momento
          fregues = Fregues(tempo_chegada + self.__lista[-1].tempo)
          entrada_lista = EntradaLista(0, fregues)
        #se o freguês em serviço termina antes de chegar alguém
        else:
          #encontramos a entrada correspondente ao freguês que estava em serviço
          #iremos disparar o evento de término de serviço desse freguês
          for (i in range(len(self.__lista)-1, -1, -1)):
            if (self.__lista[i].evento == 1):
              fregues = self.__lista[i].fregues
              break
          fregues.terminaServico(tempo_termino + self.__lista[-1].tempo)
          entrada_lista = EntradaLista(2, fregues)
    
    #uma nova pessoa começou a ser servida
    if (nova_entrada.evento == 1):
      #atualizando estado do sistema
      self.__n_pessoas_espera = self.__n_pessoas_espera - 1
      
      #preparando para gerar novo evento
      #mesmo caso para quando ocorre uma chegada na fila e já tem alguém em serviço
      tempo_chegada = self.simulaTempoAteEvento(self.__tx_chegada)
      tempo_termino = self.simulaTempoAteEvento(self.__tx_servico)
      if (tempo_chegada < tempo_termino):
        fregues = Fregues(tempo_chegada + self.__lista[-1].tempo)
        entrada_lista = EntradaLista(0, fregues)
      else:
        for (i in range(len(self.__lista)-1, -1, -1)):
          if (self.__lista[i].evento == 1):
            fregues = self.__lista[i].fregues
            break
        fregues.terminaServico(tempo_termino + self.__lista[-1].tempo)
        entrada_lista = EntradaLista(2, fregues)
      
    #uma pessoa acabou de completar seu serviço
    if (nova_entrada.evento == 2):
      #atualizando estado do sistema
      self.__n_pessoas_sist = self.__n_pessoas_sist - 1
      
      #preparando para gerar novo evento
      #caso em que tem pelo menos uma pessoa na fila de espera após termino de serviço
      #precisamos botar alguém imediatamente em serviço, dependendo da política
      if (self.__n_pessoas_espera > 0):
        #correponde a FCFS
        if (tipo_fila == 0):
          for (i in range(len(self.__lista))):
            #queremos encontrar o freguês que entrou há mais tempo na fila que ainda não foi servido
            if (self.__lista[i].evento == 0 and !self.__lista[i].fregues.entrou_em_servico):
              fregues = self.__lista[i].fregues
              break
        #corresponde a LCFS
        else:
          for (i in range(len(self.__lista)-1, -1, -1)):
            #queremos encontrar o último freguês que entrou na fila e ainda não foi servido
            if (self.__lista[i].evento == 0 and !self.__lista[i].fregues.entrou_em_servico):
              fregues = self.__lista[i].fregues
              break
        #esse freguês entra em serviço imediatamente
        fregues.entraEmServico(self.__lista[-1].tempo)
        entrada_lista = EntradaLista(1, fregues)
      #se não tiver ninguém na fila de espera temos que esperar a próxima chegada
      else:
        tempo_chegada = self.simulaTempoAteEvento(self.__tx_chegada)
        fregues = Fregues(tempo_chegada)
        entrada_lista = EntradaLista(0, fregues)
    
    #gerando novo evento
    self.addNovaEntrada(entrada_lista)
    
    
    
class ControladorFila:
  #IC indica intervalo de confiança
  #n_rodadas é o número de rodadas de simulação
  #tipo_fila == 0 indica política FCFS
  #tipo_fila == 1 indica política LCFS
  #k indica o número de coletas por rodada
  def __init__(self, tx_chegada:float, tx_servico: float, IC: float, precisao: n_rodadas: int, k: int, float, tipo_fila: int, semente: int):